### ISSUE TITLE
after running train.py it is showing Value-error y contains previously unseen labels:

### ISSUE THREAD

**Issue by prashantlv** [abhishekkrthakur/mlframework#10]
![abhi](https://user-images.githubusercontent.com/53661054/83391783-9f2ac100-a411-11ea-824d-0e9ba936f80b.png)

 
I am following your YouTube series....and this happens in episode 1. I rechecked script 10 times. It is ditto same as yours.

**Comment by abhishekkrthakur** [comment]
fillna before doing this.

**Comment by prashantlv** [comment]
> fillna before doing this.

But why your script is running in episode 1....you have written it from scratch, i was following that !!
What changes do i have to make to fillna ? do i have to write module by my own ? or you did it in some else script ??

Thanks

**Comment by prashantlv** [comment]
Done....now it's working properly. Thank you  sir
