### ISSUE TITLE
Conda env create -f environment.yml RESOLVEPACKAGENOTFOUND

### ISSUE THREAD

**Issue by yash276** [abhishekkrthakur/mlframework#11]
Hi All,
I am trying to replicate this environment in my system. I was following the steps indicated in the book. Approaching any Machine Learning Problem.
I tried running the following the command and was receiving the following error.
I have never worked with Anaconda. 
It would be great if someone can help me out.

<img width="1792" alt="Screenshot 2020-08-06 at 12 55 17 AM" src="https://user-images.githubusercontent.com/29867809/89455264-a65aac00-d77f-11ea-8ea2-1a3e314903b8.png">

**Comment by abhishekkrthakur** [comment]
did you read the README ? :)

**Comment by abhishekkrthakur** [comment]
https://github.com/abhishekkrthakur/approachingalmost

**Comment by yash276** [comment]
> did you read the README ? :)

Sorry I did not saw this repository. Let me Try and See it it works.
Thanks for the reply.

**Comment by yash276** [comment]
> did you read the README ? :)

It worked thank you so much. 
And once again sorry for raising the issue in wrong repo. 
I will close this now.
