### ISSUE TITLE
Conda environment creation failed

### ISSUE THREAD

**Issue by sugatoray** [abhishekkrthakur/mlframework#4]
At time stamp [11:14](https://www.youtube.com/watch?v=N9lo_UxSkWA&t=674s) in the youtube video: [Tips N Tricks #2: Setting up development environment for machine learning](https://www.youtube.com/watch?v=N9lo_UxSkWA&t=674s), issuing the command `conda env create -f environment.yml` throws the following error.  
```bash
Solving environment: failed
ResolvePackageNotFound:
  - python==3.7.6=h0371630_1
```

+ _Using Windows Subsystem as Linux (WSL) - Ubuntu_

**Comment by abhishekkrthakur** [comment]
Can you try change it to `python==3.7.6` ?

**Comment by abhishekkrthakur** [comment]
closing this as its stale now. feel free to re-open.

**Comment by sugatoray** [comment]
Sorry, I checked this a lot later. But thanks to this I had to work my way through managing conda environments. 

But, thanks for your reply. 😊
