### ISSUE TITLE
int() argument error

### ISSUE THREAD

**Issue by TashinAhmed** [abhishekkrthakur/mlframework#6]
File "../src/train.py", line 12, in <module>
    FOLD = int(os.environ.get("FOLD"))
**TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'**

I am having this issue.
Can anyone provide any solution?
TIA

**Comment by pravgcet** [comment]
export variable FOLD in run.sh

**Comment by mlbenoit** [comment]
> export variable FOLD in run.sh

I am running into the same issue. I have exported the variable FOLD in run.sh, but without success. 
I assume you mean "export FOLD = 0".
